# Generated by Django 4.2 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultCategoryTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Доход"),
                            ("expense", "Расход"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("color", models.CharField(default="#007BFF", max_length=7, verbose_name="Цвет")),
                ("icon", models.CharField(default="💰", max_length=50, verbose_name="Иконка")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Шаблон категории по умолчанию",
                "verbose_name_plural": "Шаблоны категорий по умолчанию",
                "ordering": ["type", "sort_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="defaultcategorytemplate",
            constraint=models.UniqueConstraint(
                fields=("type", "name"),
                name="unique_default_category_template",
            ),
        ),
    ]

