# Generated by Django 4.2 on 2026-01-14

from django.db import migrations


def seed_default_templates(apps, schema_editor) -> None:
    DefaultCategoryTemplate = apps.get_model("categories", "DefaultCategoryTemplate")

    templates = [
        # Income (3)
        {
            "name": "Зарплата",
            "type": "income",
            "icon": "💰",
            "color": "#00B894",
            "sort_order": 10,
        },
        {
            "name": "Дополнительный доход",
            "type": "income",
            "icon": "💼",
            "color": "#0984E3",
            "sort_order": 20,
        },
        {
            "name": "Прочие поступления",
            "type": "income",
            "icon": "🎁",
            "color": "#6C5CE7",
            "sort_order": 30,
        },
        # Expense (10)
        {
            "name": "Продукты",
            "type": "expense",
            "icon": "🥕",
            "color": "#FF6B6B",
            "sort_order": 10,
        },
        {
            "name": "Жильё",
            "type": "expense",
            "icon": "🏠",
            "color": "#96CEB4",
            "sort_order": 20,
        },
        {
            "name": "Транспорт",
            "type": "expense",
            "icon": "🚇",
            "color": "#4ECDC4",
            "sort_order": 30,
        },
        {
            "name": "Связь и интернет",
            "type": "expense",
            "icon": "📱",
            "color": "#45B7D1",
            "sort_order": 40,
        },
        {
            "name": "Еда вне дома",
            "type": "expense",
            "icon": "🍽",
            "color": "#FD79A8",
            "sort_order": 50,
        },
        {
            "name": "Одежда и обувь",
            "type": "expense",
            "icon": "👕",
            "color": "#DDA0DD",
            "sort_order": 60,
        },
        {
            "name": "Здоровье",
            "type": "expense",
            "icon": "💊",
            "color": "#FFEAA7",
            "sort_order": 70,
        },
        {
            "name": "Развлечения и досуг",
            "type": "expense",
            "icon": "🎉",
            "color": "#6C5CE7",
            "sort_order": 80,
        },
        {
            "name": "Подарки",
            "type": "expense",
            "icon": "🎁",
            "color": "#E17055",
            "sort_order": 90,
        },
        {
            "name": "Разное",
            "type": "expense",
            "icon": "🐙",
            "color": "#A0A0A0",
            "sort_order": 100,
        },
    ]

    for item in templates:
        DefaultCategoryTemplate.objects.get_or_create(
            type=item["type"],
            name=item["name"],
            defaults={
                "icon": item["icon"],
                "color": item["color"],
                "sort_order": item["sort_order"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_defaultcategorytemplate"),
    ]

    operations = [
        migrations.RunPython(seed_default_templates, migrations.RunPython.noop),
    ]

