# Generated by Django 4.2 on 2025-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='awaiting_category_creation',
            field=models.BooleanField(default=False),
        ),
    ]
