# Generated by Django 4.2 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_userstate_awaiting_category_creation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный ключ (например: welcome_message)",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Человеческое название (для админки)",
                        max_length=255,
                    ),
                ),
                ("text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Текст бота",
                "verbose_name_plural": "Тексты бота",
                "ordering": ["slug"],
            },
        ),
    ]

