# Generated by Django 4.2 on 2026-01-14

from django.db import migrations


def seed_bot_texts(apps, schema_editor) -> None:
    BotText = apps.get_model("telegram_bot", "BotText")

    BotText.objects.get_or_create(
        slug="welcome_message",
        defaults={
            "title": "Приветствие /start",
            "text": (
                "👋 Привет, {first_name}!\n\n"
                "💰 Я твой личный финансовый помощник FinHub!\n\n"
                "📝 Как добавлять операции:\n"
                "• 500 кофе — быстрый расход\n"
                "• +1000 зарплата — быстрый доход\n"
                "• 1500 — выбрать категорию\n\n"
                "🎯 Используй кнопки ниже или просто пиши суммы!"
            ),
            "is_active": True,
        },
    )

    BotText.objects.get_or_create(
        slug="default_categories_message",
        defaults={
            "title": "Сообщение о категориях по умолчанию",
            "text": (
                "Для экономии времени я уже создал базовые категории доходов и расходов.\n"
                "Ты можешь переименовать их, добавить свои или удалить лишние — как удобно."
            ),
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_bottext"),
    ]

    operations = [
        migrations.RunPython(seed_bot_texts, migrations.RunPython.noop),
    ]

